"""empty message

Revision ID: 13d8c4ea9499
Revises: a5cffa318ac2
Create Date: 2024-12-17 11:59:39.852180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13d8c4ea9499'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('biome', sa.Enum('Dessert', 'Forest', 'Frozen', 'Volcanic',name = 'biome_enum'), nullable=True),
    # biome = db.Column(Enum('Dessert', 'Forest', 'Frozen', 'Volcanic', name='biome_enum'), nullable=False)  
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planets')
    # ### end Alembic commands ###
