"""empty message

Revision ID: 199f1643fe02
Revises: 34cc831f90cb
Create Date: 2024-12-17 18:08:37.282414

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '199f1643fe02'
down_revision = '34cc831f90cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('biome', sa.Enum('Dessert', 'Forest', 'Frozen', 'Volcanic', name='biome_enum'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('biome')

    # ### end Alembic commands ###
